### ISSUE TITLE
Autocite errors

### ISSUE THREAD

**Issue by gwaygenomics** [greenelab/lab-website-template#96]
Hi @vincerubinetti - I am documenting an error that I just ran into. I haven't dug deeply into resolving it yet, but I figured I'd post here in case 1) you know of a quick solution or 2) someone else runs into this issue and I can track my progress solving it here.

I am trying to get autocite to work and I am getting two errors, which may or may not be related. 

First, as specified in the [`Basic Use` docs](https://github.com/greenelab/lab-website-template/wiki/Automatic-Citations#basic-use) I am pushing code to WayScience/waysciencelab.com#1 and receiving the following error, associated with the `git-auto-commit-action` github action.

```
Run stefanzweifel/git-auto-commit-action@v4
  with:
    file_pattern: _data/citations.yaml
    commit_message: Generate citations
    push_options: --force
    branch: init
    repository: .
    commit_user_name: GitHub Actions
    commit_user_email: actions@github.com
    commit_author: gwaygenomics <gwaygenomics@users.noreply.github.com>
    skip_dirty_check: false
    skip_fetch: false
    disable_globbing: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.11/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.11/x64/lib
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_STATUS_OPTIONS: 
INPUT_BRANCH value: init
From https://github.com/WayScience/waysciencelab.com
 * [new branch]      main       -> origin/main
error: pathspec 'init' did not match any file(s) known to git
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

Second, I am trying to compile the citations manually by using `bash cite.sh` and run into what seems to be a manubot error:

```bash
(base) greg@Gregorys-MacBook waysciencelab.com % bash cite.sh

COMPILING LIST OF SOURCES TO CITE

RUNNING SOURCES PLUGIN

  ../_data/sources.yaml
    arxiv:2104.11364
    doi:10.1002/1873-3468.14067
    doi:10.1091/mbc.E20-12-0784

  Got 3 sources

GENERATING CITATIONS FOR SOURCES

  Source 1 of 3 - arxiv:2104.11364
    Using Manubot to generate new citation
    Manubot could not generate citation
```

No matter which order I put the sources, I receive the same error at "Source 1 of 3".

**Comment by gwaygenomics** [comment]
Update on manubot error: it seems to have resolved, in some unknown way. I am still struggling with the `git-auto-commit-action`.

I did two things that I know of, and perhaps one or more mysterious things.

## First attempt

```bash
# First, I tried running the preferred citation formatter, as specified in the action
python auto-cite/auto-cite.py
```

This ran into the same error as `bash cite.sh`.

## Second attempt

I noticed that my arxiv id was missing the version tag, so I fixed it in WayScience/waysciencelab.com/1@b52c1087288b5980c203c2d971ce6fde62e3d021 and reran `auto-cite.py`. I received the same error.

## Resolution of Manubot error

I then moved on to try to resolve the github action bug by testing several ideas found in https://github.com/stefanzweifel/git-auto-commit-action (they're documented in my PR), but none worked.

However, somewhere along the way I tried compiling citations again and it somehow worked! I do not believe I changed anything in the sources yaml, but I did reinstall manubot.

So, either reinstalling manubot worked _or_ somehow running the same code more than once resolved the issue.

**Comment by vincerubinetti** [comment]
Regarding the Manubot cite errors, that is most likely an upstream error with Manubot itself or one of the services it relies on like Crossref. Did you try running Manubot directly like `manubot cite arxiv:2104.11364` at the time when it wasn't working?

Also FYI, running `cite.sh` is just a shorthand for `python auto-cite/auto-cite.py`, so that will always be the same result.

Regarding the errors with the action. I see you're working from a fork of your website rather than a branch. Did you make sure to [enable GitHub actions on the fork repo before opening the pull request](https://github.com/greenelab/lab-website-template/wiki/Get-Started#on-your-computer)? I'm looking through the errors in your github actions, and there's a lot of changes so it's hard to tell what happened. But usually that `pathspec` error occurs when the `stefanzweifel/git-auto-commit-action` doesn't have the permissions to write, which can happen when you're working from a fork and haven't enabled gh-actions before the pr.

**Comment by vincerubinetti** [comment]
One strange thing is you were getting an error about the input branch being `init`, and it doesn't look like you were setting that in the `stefanzweifel/git-auto-commit-action` or anything. Which btw, you should never need to customize the options for that; it's supposed to commit to the same branch that it's currently on (whatever branch triggered the workflow run, be that a straight commit to `main` or a pull request branch).

**Comment by gwaygenomics** [comment]
Thanks @vincerubinetti !

> Did you try running Manubot directly like manubot cite arxiv:2104.11364 at the time when it wasn't working?

I did not.

> But if it would help, I could point to the place in the code where you could explicitly show the error Manubot threw when running auto-cite.

I think it might... perhaps adding `--verbose` flag functionality would do the trick. I actually just ran into this just now and received the following error:

```bash
COMPILING LIST OF SOURCES TO CITE

RUNNING SOURCES PLUGIN

  ../_data/sources.yaml

    Can't parse ../_data/sources.yaml. Make sure it's valid YAML.
```

It would have been helpful to know that line 196 was invalidating the YAML. (I am not sure if Manubot would tell you that by default)

> Did you make sure to enable GitHub actions on the fork repo before opening the pull request? But usually that pathspec error occurs when the stefanzweifel/git-auto-commit-action doesn't have the permissions to write, which can happen when you're working from a fork and haven't enabled gh-actions before the pr.

Pretty sure I did! But I am about to file a new PR, so we'll see if the errors persist.

**Comment by gwaygenomics** [comment]
Autocite failed in new pull request WayScience/waysciencelab.com#2

```bash
Run stefanzweifel/git-auto-commit-action@v4
  with:
    file_pattern: _data/citations.yaml
    commit_message: Generate citations
    push_options: --force
    branch: update-round-2
    repository: .
    commit_user_name: GitHub Actions
    commit_user_email: actions@github.com
    commit_author: gwaygenomics <gwaygenomics@users.noreply.github.com>
    skip_dirty_check: false
    skip_fetch: false
    disable_globbing: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.11/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.11/x64/lib
From https://github.com/WayScience/waysciencelab.com
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
 * [new branch]      main       -> origin/main
INPUT_REPOSITORY value: .
INPUT_STATUS_OPTIONS: 
INPUT_BRANCH value: update-round-2
error: pathspec 'update-round-2' did not match any file(s) known to git
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by vincerubinetti** [comment]
I'm still looking into this, but in the future, can you try doing pull requests from branches of the same repo instead of from a fork. 

`git-auto-commit` has had warnings in the past that forks may not work. With the instruction to enable github actions first, I was able to make it work consistently with a fork during my testing. But maybe that is no longer the case. Maybe there was a change to the action that made it stop working.

**Comment by gwaygenomics** [comment]
Just confirmed in WayScience/waysciencelab.com#7 that a PR from a branch enables the autocite action.

Thanks!
